---
filing_status_mapper:
  po_thresh:
    '1': po_thresh_single
    '2': po_thresh_married
    '3': po_thresh_married / 2
    '4': po_thresh_single

value_young:
  value: 
    '2014': [1000, 0]
    '2018': [2000, 0]
    '2021': [2000, 1600]
    '2022': [2000, 0]
    '2026': [1000, 0]

value_old:
  value:
    '2014': [1000, 0]
    '2018': [2000, 0]
    '2021': [2000, 1000]
    '2022': [2000, 0]
    '2026': [1000, 0] 

young_age_limit:
  value: 5
  
old_age_limit:
  value:
    '2014': 17
    '2021': 18
    '2022': 17

po_thresh_single:
  value:
    '2014': [75000, Inf]
    '2018': [200000, Inf]
    '2021': [200000, 112000]
    '2022': [200000, Inf]
    '2026': [75000, Inf]
    
po_thresh_married:
  value:
    '2014': [110000, Inf] 
    '2018': [400000, Inf]
    '2021': [400000, 150000]
    '2022': [400000, Inf]
    '2026': [110000, Inf]

po_rate:
  value: [0.05, 0.05]

value_other:
  value:
    '2014': 0
    '2018': 500
    '2026': 0

fully_refundable:
  value:
    '2014': False
    '2021': True 
    '2022': False
    
pi_rate:
  value: 0.15
  
pi_thresh:
  value:
    '2014': 3000
    '2018': 2500
    '2026': 3000

max_refund:
  value:
    '2014': Inf
    '2018': 1400
    '2026': Inf
  i_measure:
    '1987': cpi
    '2017': chained_cpi
  i_base_year: 2017
  i_direction: -1
  i_increment: 100
  
need_ssn:
  value:
    '2014': False
    '2018': True
    '2026': False
